# Generated by Django 5.0.6 on 2024-05-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('location', models.CharField(max_length=40)),
                ('status', models.BooleanField()),
                ('room_type', models.CharField(choices=[('YAC', 'AC'), ('NAC', 'NON-AC')], max_length=40)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rooms',
                'verbose_name_plural': 'Rooms',
            },
        ),
    ]
