# Generated by Django 5.0.3 on 2024-05-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Rooms', 'verbose_name_plural': 'Rooms'},
        ),
    ]
