# Generated by Django 5.0.3 on 2024-05-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Users', 'verbose_name_plural': 'Users'},
        ),
    ]
