# Generated by Django 5.0.3 on 2024-03-13 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_by', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('booked_on', models.DateField()),
                ('reason', models.TextField(max_length=50)),
                ('checked_in', models.DateField()),
                ('is_accepted', models.BooleanField()),
                ('room_no', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail', models.CharField(max_length=40)),
                ('phone_no', models.IntegerField(max_length=10)),
                ('resident_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='BookStatus.bookingstatus')),
            ],
        ),
    ]
