# Generated by Django 5.0.6 on 2024-05-21 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_by', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('booked_on', models.DateField(auto_now_add=True)),
                ('reason', models.TextField(max_length=50)),
                ('checked_in', models.BooleanField(default=False)),
                ('checked_out', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('e_mail', models.CharField(default=False, max_length=40)),
                ('phone_no', models.IntegerField(default=False)),
                ('room_no', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Rooms.room')),
            ],
        ),
    ]
