# Generated by Django 5.0.6 on 2024-07-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookStatus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingstatus',
            options={'verbose_name': 'Booking Status', 'verbose_name_plural': 'Booking Status'},
        ),
    ]
