# Generated by Django 5.0.3 on 2024-05-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=40)),
                ('number_guest', models.IntegerField()),
                ('reason', models.CharField(max_length=40)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
            ],
            options={
                'verbose_name': 'Requests',
                'verbose_name_plural': 'Requests',
            },
        ),
    ]
