# Generated by Django 5.0.3 on 2024-06-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0002_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='statussssss',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
