# Generated by Django 5.0.3 on 2024-06-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0003_request_statussssss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='statussssss',
        ),
    ]
